name: Test
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run test
        uses: borales/actions-yarn@v4
        with:
          cmd: test